# Generated by Django 2.1.4 on 2019-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DialogflowApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reqLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=23)),
                ('responseId_req', models.CharField(max_length=50)),
                ('queryText_req', models.CharField(max_length=300)),
                ('param_req', models.CharField(max_length=500)),
                ('webhook_latency_ms', models.CharField(max_length=50)),
                ('languageCode_req', models.CharField(max_length=10)),
                ('intent_displayName_req', models.CharField(max_length=100)),
            ],
        ),
    ]
