# Generated by Django 2.1.4 on 2019-03-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DialogflowApi', '0002_reqlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqlog',
            name='webhook_latency_ms',
        ),
    ]
