# Generated by Django 2.1.4 on 2019-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirData_airkorea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('Air_So2', models.CharField(max_length=10)),
                ('Air_So2_Context', models.CharField(max_length=40)),
                ('Air_Co', models.CharField(max_length=10)),
                ('Air_Co_Context', models.CharField(max_length=40)),
                ('Air_O3', models.CharField(max_length=10)),
                ('Air_O3_Context', models.CharField(max_length=40)),
                ('Air_No2', models.CharField(max_length=10)),
                ('Air_No2_Context', models.CharField(max_length=40)),
                ('Air_PM10', models.CharField(max_length=10)),
                ('Air_PM10_Context', models.CharField(max_length=40)),
                ('Air_PM25', models.CharField(max_length=10)),
                ('Air_PM25_Context', models.CharField(max_length=40)),
                ('Air_Khai', models.CharField(max_length=10)),
                ('Air_Khai_Context', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AirData_airkorea_forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('Air_PM10_forecast', models.CharField(max_length=10)),
                ('Air_PM10_forecast_Context', models.CharField(max_length=40)),
                ('Air_PM25_forecast', models.CharField(max_length=10)),
                ('Air_PM25_forecast_Context', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Health_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('inflWho', models.CharField(max_length=10)),
                ('AsthmaWho', models.CharField(max_length=10)),
                ('BrainWho', models.CharField(max_length=10)),
                ('SkinWho', models.CharField(max_length=10)),
                ('FlowerWoodyWho', models.CharField(max_length=10)),
                ('FlowerPineWho', models.CharField(max_length=10)),
                ('FlowerWeedsWho', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Living_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('fsnLife', models.CharField(max_length=10)),
                ('Senso_temLife', models.CharField(max_length=10)),
                ('HeatLife', models.CharField(max_length=10)),
                ('DsplsLife', models.CharField(max_length=10)),
                ('UltrvLife', models.CharField(max_length=10)),
                ('WinterLife', models.CharField(max_length=10)),
                ('AirpllutionLife', models.CharField(max_length=10)),
                ('Senso_HeatLife', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealData_Neis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('Mon', models.CharField(max_length=200)),
                ('Tue', models.CharField(max_length=200)),
                ('Wed', models.CharField(max_length=200)),
                ('Thu', models.CharField(max_length=200)),
                ('Fri', models.CharField(max_length=200)),
                ('Sat', models.CharField(max_length=100)),
                ('Sun', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealData_Neis_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('Mon', models.CharField(max_length=300)),
                ('Tue', models.CharField(max_length=300)),
                ('Wed', models.CharField(max_length=300)),
                ('Thu', models.CharField(max_length=300)),
                ('Fri', models.CharField(max_length=300)),
                ('Sat', models.CharField(max_length=150)),
                ('Sun', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_skplanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('Date', models.CharField(max_length=12)),
                ('Time', models.CharField(max_length=7)),
                ('station_name', models.CharField(max_length=15)),
                ('station_type', models.CharField(max_length=8)),
                ('wind_wdir', models.CharField(max_length=8)),
                ('wind_wspd', models.CharField(max_length=5)),
                ('snowrain_sinceOntime', models.CharField(max_length=5)),
                ('snowrain_type', models.CharField(max_length=1)),
                ('sky_name', models.CharField(max_length=10)),
                ('rain_sinceMidnight', models.CharField(max_length=5)),
                ('temperature_tc', models.CharField(max_length=8)),
                ('temperature_tmax', models.CharField(max_length=8)),
                ('temperature_tmin', models.CharField(max_length=8)),
                ('humidity', models.CharField(max_length=8)),
                ('pressure_surface', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_skplanet_en',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=18)),
                ('Date', models.CharField(max_length=12)),
                ('Time', models.CharField(max_length=7)),
                ('station_name', models.CharField(max_length=30)),
                ('station_type', models.CharField(max_length=8)),
                ('wind_wdir', models.CharField(max_length=8)),
                ('wind_wspd', models.CharField(max_length=5)),
                ('snowrain_sinceOntime', models.CharField(max_length=5)),
                ('snowrain_type', models.CharField(max_length=1)),
                ('sky_name', models.CharField(max_length=15)),
                ('rain_sinceMidnight', models.CharField(max_length=5)),
                ('temperature_tc', models.CharField(max_length=8)),
                ('temperature_tmax', models.CharField(max_length=8)),
                ('temperature_tmin', models.CharField(max_length=8)),
                ('humidity', models.CharField(max_length=8)),
                ('pressure_surface', models.CharField(max_length=10)),
            ],
        ),
    ]
