# Generated by Django 2.1.4 on 2019-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=23)),
                ('Log_Type', models.CharField(max_length=10)),
                ('Data', models.CharField(max_length=200)),
                ('TextData', models.TextField(null=True)),
            ],
        ),
    ]
