# Generated by Django 2.1.4 on 2019-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KakaoApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reqLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_name', models.CharField(max_length=50)),
                ('utterance', models.CharField(max_length=4000)),
                ('bot_userID', models.CharField(max_length=50)),
                ('plusfriendUserKey', models.CharField(max_length=50)),
                ('appUserId', models.CharField(max_length=50)),
            ],
        ),
    ]
