# Generated by Django 2.1.4 on 2019-03-30 14:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KakaoApi', '0002_reqlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqlog',
            name='detailParams',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
