# Generated by Django 2.1.4 on 2019-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KakaoApi', '0003_reqlog_detailparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqlog',
            name='bot_userID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reqlog',
            name='utterance',
            field=models.TextField(null=True),
        ),
    ]
